name: trustworky_flutterfire
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  rxdart: ^0.21.0
  provider: ^4.0.0
  font_awesome_flutter: ^8.5.0
  flutter_launcher_icons: ^0.7.4
  bubble_bottom_bar: ^1.2.0
  intl: ^0.15.8
  flutter_form_builder: ^3.7.2
  multi_page_form: ^1.0.4
  google_fonts: ^0.2.0
  flutter_auth_buttons: ^0.6.0
  uuid: ^2.0.4
  floating_search_bar: ^0.2.0
  flutter_svg: ^0.15.0
  time_formatter: ^1.0.0+5
  bubble: ^1.1.9+1
  chatbar: ^0.0.7
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  image_picker: ^0.6.2+3
  firebase_storage: ^3.1.1
  fluttertoast: ^3.1.3
  photo_view: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icon/icon.png

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product-sans/Product-Sans-Regular.ttf
        - asset: assets/fonts/product-sans/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/product-sans/Product-Sans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

